apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-webhook-service
  labels:
    app: transaction-webhook-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-webhook-service
  template:
    metadata:
      labels:
        app: transaction-webhook-service
    spec:
      containers:
      - name: transaction-webhook-service
        image: transaction-webhook-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: url
        - name: REDIS_HOST
          value: "redis-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-webhook-service
spec:
  selector:
    app: transaction-webhook-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
